### ISSUE TITLE
Attach videos to report

### ISSUE THREAD

**Issue by Haemoglobin** [Tallyb/cucumber-playwright#148]
Just in case you weren't aware, I found it's possible to attach videos to the cucumber report using the following: 

import { promisify } from 'util'; 
import { readFile } from 'fs'; 

... 
const video = await this.page?.video(); 
const videoPath = await video?.path(); 
if (videoPath) {
  const videoBuffer = await promisify(readFile)(videoPath);
  video && (await this.attach(videoBuffer, "video/webm"))
}

Pretty neat!

**Comment by Tallyb** [comment]
That is really neat. 
With the new trace option, the video attachment seems less attractive. 
I will close the issue and keep it here so people can reference it if they would like to do it themselves
