### ISSUE TITLE
Is it possible to use the playwright "projects" feature with cucumber?

### ISSUE THREAD

**Issue by craigvl** [Tallyb/cucumber-playwright#206]
Hello,

Firstly thank you for this template. Secondly, we are looking to see if we can use cucumber with our current playwright implementation and the thing that we rely on at the moment is the concept of "projects":

https://playwright.dev/docs/test-advanced#projects

We use this feature to allow us to get playwright to spin up all different browsers with different resolutions:

``` 
projects: [
        //
        //  Chrome
        //
        {
            name: 'Chromium-Mobile-S',
            timeout: timeout,
            use: {
                // Configure the browser to use.
                browserName: 'chromium',
                headless: headless,
                viewport: { width: 320, height: 785 },
                isMobile: true,
                hasTouch: true
                // Any Chromium-specific options.
            },
        },
        {
            name: 'Chromium-Mobile-M',
            timeout: timeout,
            use: {
                // Configure the browser to use.
                browserName: 'chromium',
                headless: headless,
                viewport: { width: 375, height: 785 },
                isMobile: true,
                hasTouch: true
            },
        },
        {
            name: 'Chromium-Mobile-LG',
            timeout: timeout,
            use: {
                // Configure the browser to use.
                browserName: 'chromium',
                headless: headless,
                viewport: { width: 425, height: 785 },
                isMobile: true,
                hasTouch: true
            },
        ,
        // "iPhone 11" tests use WebKit browser.
        {
            name: 'iPad pro 11 landscape',
            timeout: timeout,
            use: {
                browserName: 'webkit',
                ...devices['iPad Pro 11 landscape'],
                headless: headless
            },
        }
    ],
};
```

I am trying to understand if this would be possible with this template or is this something that the playwright test runner is providing and something that the cucumber runner cannot provide?

**Comment by Tallyb** [comment]
Interesting... 
My first response was that Playwright test and Cucumber are both test runners, and as such is not meant to work together (not to be confused with Playwright which is browser automation). 
The projects "equivalent" in Cucumber is defining different profiles in the cucumber.js file: https://github.com/cucumber/cucumber-js/blob/main/docs/profiles.md

Having said that, it might be interesting to provide a simple way to provide a set of default parameters that will be moved from the profiles to the world.

**Comment by AndyGBC** [comment]
> Thanks, after looking into this a little more it seems that we lose quite a but of functionality by not using the playwright test runner, given this we have decided to cheat a little at the moment and use the playwright test runner but add comments and method calls to mimic a cucumber style, like below:
> 

I am having exactly the same issue as you @craigvl.

I really hope there is some kind of proper integration between Playwright test and cucumber to allow it to work using the config projects setup.

**Comment by Tallyb** [comment]
I am wondering if the extensions to profiles in cucumbers 8 can be the solution? https://github.com/cucumber/cucumber-js/blob/main/docs/profiles.md#profiles

**Comment by Tallyb** [comment]
@AndyGBC  @craigvl - thank you for your feedback. I suggest posting on the Playwright discussions a request for supporting cucumber syntax in PW Test. Maybe they will do it...

**Comment by kumars3** [comment]
@AndyGBC ; @craigvl ; @Tallyb 
I have posted this request as a feature to add in playwright github page. Hopefully, playwright devs will look into this.
https://github.com/microsoft/playwright/issues/12069

cc: @dgozman; @aslushnikov; @mxschmitt

**Comment by Akupsmee** [comment]
Thanks guys, your comments have been helpful. 
i am also trying to integrate playwright and cucumber for my api tests. Hope we get a better syntax integration.
