### ISSUE TITLE
Pass CLI parameter

### ISSUE THREAD

**Issue by Awaras** [Tallyb/cucumber-playwright#222]
First of all, thank you so much for this framework. This is exactly what I needed.

I have a question on passing parameters via cli. 

If I need to run test with some params for example, cucumber-js --param.env='test' How would I do that ?

**Comment by Tallyb** [comment]
passing cli params is not that great on cucumber.js. I use env params.

**Comment by Awaras** [comment]
ok, thank you for the reply.
