### ISSUE TITLE
Parallel execution

### ISSUE THREAD

**Issue by Haemoglobin** [Tallyb/cucumber-playwright#266]
Hi, 

It seems the Playwright test runner support [parallel execution](https://playwright.dev/docs/test-parallel/). 

I thought I would try doing something similar in this setup by making use of the new cucumber-js [parallel flag](https://github.com/cucumber/cucumber-js/blob/main/docs/parallel.md) by changing the line in package.json to: 
"all": "cucumber-js features/**/*.feature --parallel 2"  

However I get a browserType.launch timeout error when I try. 

This would be really useful to have on as test packs grow, do you have any idea what could be happening here? I tried turning on DEBUG='pw:api,pw:browser*' however it didn't seem to give any clues. It just closes the browser process for no apparent reason immediately after opening it. 

Thanks

**Comment by Tallyb** [comment]
--parallel=2 should work.

**Comment by Haemoglobin** [comment]
This works great actually - sorry for the late reply 👍
