### ISSUE TITLE
Is it possible to create allure report using this template?

### ISSUE THREAD

**Issue by alikhanm86** [Tallyb/cucumber-playwright#269]
Hi Tally Barak,
First of all big thanks for this template!!

I took a clone of this and trying to generate allure report but no luck. I’ve tried the below link

https://github.com/allure-framework/allure-js/blob/master/packages/allure-cucumberjs/README.md

For me “allure-results” folder is getting generated, but it’s empty. So I was confused if there is something wrong at my end or if such integration itself is not in place as of now.

Could you please help me generate allure report?

Regards,
Ali Khan.

**Comment by zepouet** [comment]
Hello,

Maybe you need to uncomment the line 19 from https://github.com/Tallyb/cucumber-playwright/blob/master/cucumber.mjs
As explained in the documentation, only one output format is possible

```
The last reporter/formatter found on the cucumber-js command-line wins:
````

Thanks
