### ISSUE TITLE
Is it possible to compare screenshots with this project?

### ISSUE THREAD

**Issue by pris0213** [Tallyb/cucumber-playwright#318]
Playwright Test includes the ability to produce and visually compare screenshots using `expect(value).toMatchSnapshot(snapshotName)`. More information on this article: [Visual comparisons | Playwright](https://playwright.dev/docs/test-snapshots).

Since Cucumber replaces Playwright Test in this project, is there an alternative way to do this? Do you have plans on supporting these Playwright Test additional functions?

Best wishes,
Priscila.

**Comment by Tallyb** [comment]
check out this PR: https://github.com/Tallyb/cucumber-playwright/pull/336

**Comment by Tallyb** [comment]
Screenshots were added to the repo
