### ISSUE TITLE
Is it possible to use playwright testrunner with the cucumber set up?

### ISSUE THREAD

**Issue by mareru** [Tallyb/cucumber-playwright#331]
Since Playwright team released all the cool new features with the test runner, would it be possible that you upgrade to  this using it? Or maybe create another demo with that set up? :D Just asking

**Comment by Tallyb** [comment]
Cucumber test runner is an alternative to the playwright test runner. I agree that they are doing an amazing job there... Anything specific you would like to see? maybe there is a way to implement it with  Cucumber

**Comment by mareru** [comment]
Aha, I was not aware of it. I just like the Gherkin style of Cucumber and steps so I thought that could be used along side with all the cool features that Playwright test runner offers. :D
