### ISSUE TITLE
Playwright Test did not expect test.describe() to be called here.

### ISSUE THREAD

**Issue by cyranoDeCasa** [Tallyb/cucumber-playwright#378]
Hello,
I can't run a suite test when using test.describe
"Playwright Test did not expect test.describe() to be called here."
i tried all options, 
how we can use test.describe here ?

Thank you!

**Comment by Tallyb** [comment]
Playwright cucumber does not use test.describe, but rather it runs cucumber feature files. You can consult the cucumber documentation and the examples in this repo to see how it should work.

**Comment by cyranoDeCasa** [comment]
Thank you Tally for your response !
