### ISSUE TITLE
[question] how can we use cookies with cucumber?

### ISSUE THREAD

**Issue by cyranoDeCasa** [Tallyb/cucumber-playwright#402]
I have an issue that i can't understand

× Then I reload cookies # src\step_definitions\steps\My_steps.ts:81
       Error: function uses multiple asynchronous interfaces: callback and promise
       to use the callback interface: do not return a promise
       to use the promise interface: remove the last argument to the function

i would like to skip login with using authentification from setted cookies, but it doesn't work, it's fail in `Then('I reload cookies', async function({browser}){
    const context = await browser.newContext({
............
`

Scenario: Test
  Given I am logged in test windows
  Then I reload cookies

the step_definition:

/******* TEST LOGOUT AND reopen with COOKIES */
  Given('I am logged in test windows', async function () {
    const page = this.page!;

    await page.locator(".selector", {hasText: 'user'}).click();
    await page.locator("div:nth-of-type(3)", {hasText: 'Log out'}).click();
  });

  Then('I reload cookies', async function({browser}){
    const context = await browser.newContext({
      storageState: "auth.json"
    })
    const page = await context.newPage();
    await page.goto("http://internal.test.local/");

  })

thankyou for your help!

**Comment by Tallyb** [comment]
Not sure this is cucumber specific.
