### ISSUE TITLE
undefined issue

### ISSUE THREAD

**Issue by noneed10** [Tallyb/cucumber-playwright#492]
I tried to implement this project https://github.com/Tallyb/cucumber-playwright on my computer but I fixed all config issues I did not fix the undefined issue because this project does not use glue so How can I fix this problem? Thanks. 
![image](https://user-images.githubusercontent.com/69457534/187042335-e0c07ba5-f21d-45b6-95d5-a4d4eacb16b6.png)
![image](https://user-images.githubusercontent.com/69457534/187042345-ac49c0b9-1b5f-42c0-8344-1fd2bae59266.png)

**Comment by Tallyb** [comment]
Do you have a cucumber extension installed?

**Comment by noneed10** [comment]
![image](https://user-images.githubusercontent.com/69457534/187046227-dad6c851-efed-46a2-8217-f42223d40d60.png)
Hi Tally,
Yes it installed.

**Comment by Tallyb** [comment]
As you can see on the CI, it is working ok. The one thing I can think of - what is your node version? the cucumber configuration is in mjs file, so the minimum should be node 14.
