### ISSUE TITLE
TypeError: Cannot read property 'goto' of undefined at CustomWorld

### ISSUE THREAD

**Issue by Abimanyu3118** [Tallyb/cucumber-playwright#544]
Getting TypeError: Cannot read property 'goto' of undefined at CustomWorld. <anonymous> when I use the below snippet in playwright

async function (this: ICustomWorld, url: string){
const { page } = this;
await page!.goto(url);
}

I have used the same code in custom-world.ts just like you.

@Tallyb  Can you please assist?

**Comment by Tallyb** [comment]
Is this function supposed to be a step? you are not using the Cucumber keyword here, nor a step definition. Probably your first parameter is undefined.

**Comment by Tallyb** [comment]
Can you provide the full code? 
this does not look like a step

**Comment by harishmandal** [comment]
How to handle Multiple tab in this.. could you please help me.
