### ISSUE TITLE
npm run debug features/playwright.feature  not open headed mode

### ISSUE THREAD

**Issue by pranitcode** [Tallyb/cucumber-playwright#580]
npm run debug features/playwright.feature 

> cucumber-playwright@1.2.0 debug
> PWDEBUG=1 DEBUG=pw:api cucumber-js features/playwright.feature

'PWDEBUG' is not recognized as an internal or external command,
operable program or batch file.

**Comment by pranitcode** [comment]
I am runing on windows

**Comment by Tallyb** [comment]
you need to use the windows way of setting environment variables: set MY_VAR=hello

**Comment by pranitcode** [comment]
hay tally I set environment variables: set MY_VAR=hello in my system then I  run command npm run debug again,  but it not working. 
If I am doing wrong in it ,  please let me know , please explain in details.
![Screenshot (400)](https://user-images.githubusercontent.com/61083651/212648242-9afbdd5e-78ab-4fcb-843d-507c56d4d125.png)

**Comment by NerdishShah** [comment]
> PWDEBUG

Use windows based style to set your environment variable i.e. 
update your package.json as
`    "api": "set PWDEBUG=1&&DEBUG=pw:api cucumber-js",
`

Notice that there's no space between '&&' and 'DEBUG'
