### ISSUE TITLE
is it possible playwright reporter can be used in cucumber js

### ISSUE THREAD

**Issue by bodycombathuang** [Tallyb/cucumber-playwright#585]
I created project similar to yours, and use cucumber js test runner and cucumber report 

but cucumber report does not show whether each expression (such as page.goto, locator.click expression) in test run succeeds like playwright report

is it possible playwright reporter can be used in cucumber js , and how to implement?

**Comment by Tallyb** [comment]
https://github.com/Tallyb/cucumber-playwright#can-we-use-xxx-from-playwright-in-the-playwright-cucumber-project
