### ISSUE TITLE
How to call and Mock APIs ?

### ISSUE THREAD

**Issue by emnabn** [Tallyb/cucumber-playwright#589]
Hello,
I have the same architecture as you for my project playwright/cucumber JS but calling and mocking APIs is not working for me, For api part I added: 
1/in **common-hooks.ts**

`this.server = await request.newContext({
    baseURL: config.BASE_API_URL,
  });`

2/ in **config.ts**

>  `export const config = {
>    browser: process.env.BROWSER || 'chrome',
>    browserOptions,
>   BASE_API_URL: 'basic url',
>  };`

3/ in **custom-world.ts**

> `export interface CustomWorld extends IWorld {
>   debug: boolean;
>   urlRedirection?: string | null;
>   urlCurrent?: string;
>   urlDeal?: string | null;
>   feature?: messages.Pickle;
>   context?: BrowserContext;
>   page?: Page;
>   brand?: string;
>   testName?: string;
>   startTime?: Date;
>   server?: APIRequestContext;
>   playwrightOptions?: PlaywrightTestOptions;
> }`

4/ in **steps** to call get api: 

> `Given('A user from {string} on the results page', async function(
>   this: CustomWorld,
>   brand: string,
> ) {
>   this.brand = brand;
>   const page = this.page!;
>   await page.goto(this.parameters.appurl);
>   const response = await this.server?.get('offers', {
>     params: {
>       'country-of-residence': 'FR',
>       'driver-age': '26',
>     },
>     headers: {
>       'content-type': 'application/json',
>     },
>   });
>   expect(response).toBeDefined();`

To read json I added this code but not work:
`console.log(await this.response.json());
  expect(this.response.status()).toBe(200);`
For mocking I added this code: 

> `await page.route(
>     '**/offers',
>     async route => {
>       //  const response = await page.request.fetch(route.request());
>       route.fulfill({
>          response,
>         path: 'booksAPI.json',
>       });
>     },
>   );`

with creation of booksAPI.json file.
Here the call of api and the mock is not working, also json is not reading, @Tallyb  can you help me please? thanks

**Comment by Tallyb** [comment]
where did you add the last part?

**Comment by Tallyb** [comment]
If I understand correctly the page.goto is triggering the route changes, so you need to put them in a Promsie.all: 
```
Given('A user from {string} on the results page', async function(  this: CustomWorld, brand: string, ) { 
const {page!} = this; 
const [response ] = await Promise.all({
   page.route( 'https:real api', async route => { route.fulfill({ path: 'booksAPI.json', status: 200, contentType: 'application-json', }); }),
  page.goto(this.parameters.deeplinkSearchUrl); }
}
console.log('mocked response', response);
```
or do I miss something?
