### ISSUE TITLE
supporting many browsers as cmd command

### ISSUE THREAD

**Issue by Alje001** [Tallyb/cucumber-playwright#60]
Hi tally, 

thank you for providing this template to write cucumber tests with playwright. 
I would like to ask you if you have an example to make this template able to run tests on different browsers via cmd.
For example npm run test  --browsers chrome or npx cucumber-js --browsers firefox

I saw the part where you define the browser in common-hooks as a static values. 
```declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace NodeJS {
    interface Global {
      browser: **ChromiumBrowser**; //change to your favorite browser
    }
  }
}
const browserOptions: LaunchOptions = {
  slowMo: 1000,
  headless: false,
  channel: 'msedge', // or 'msedge', 'chrome-beta', 'msedge-beta', 'msedge-dev', etc.
  args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream'],
};

BeforeAll(async function () {
  global.browser = await **chromium**.launch(browserOptions); //change to your favorite browser
});
```
can we make it configurable via command line ? 

thank you for supporting. 

best regards
AlJendi

**Comment by Tallyb** [comment]
Hi, that is a great idea. In a few days, I will participate in a pair programming cast and will do this fix.

**Comment by Tallyb** [comment]
Implemented with https://github.com/Tallyb/cucumber-playwright/pull/69
