### ISSUE TITLE
How to attach videos to allure reporter??

### ISSUE THREAD

**Issue by samplehub** [Tallyb/cucumber-playwright#636]
Hi , I am able to get the reporter and all the attachments, screenshots. 
I am struggling to attach videos to the reporter. 
Can you please let me know if you have tried this??
Thanks

**Comment by Tallyb** [comment]
I did not. I think this issue is more appropriate in the allure repo.

**Comment by goyalvipul** [comment]
Hey @samplehub To attach the screenshots with allure report, you need to attach them to cucumber basic report.
Consider allure a wrapper over cucumber, reading the cucumber generated results. If you are able to do so, allure will auto pull the screenshots.

**Comment by goyalvipul** [comment]
@Tallyb You can fix this by implementing the above in your code. Not an issue with allure for sure.

**Comment by Tallyb** [comment]
@goyalvipul  - can you make a PR?
