### ISSUE TITLE
Every scenario create a new context

### ISSUE THREAD

**Issue by Pi-fe** [Tallyb/cucumber-playwright#673]
Hi, in my project I have a number of scenarios that make up an entire e2e stream, but if I launch the test battery it creates a new context for each scenario, how can I have a context created for file features?

**Comment by Tallyb** [comment]
Cucumberjs does not have the concept of a "before feature" so it only knows to run things on each scenario separately.

**Comment by Pi-fe** [comment]
mmh ok, I resolve it.
I moved the context creation to the beforeall and the closing to the afterall
