### ISSUE TITLE
Change expect timeout

### ISSUE THREAD

**Issue by Pi-fe** [Tallyb/cucumber-playwright#674]
Hi!
In my project  I have expect that exceeds 5 seconds, how can i change the playwright settings with cucumber.
(I already changed the setDefaultTimeout)

Thank you :)

**Comment by Tallyb** [comment]
if it is only a single expect - you can put it in the relevant step. I am not sure the global timeout for PW can be changed.

**Comment by Pi-fe** [comment]
Yes, there are many expect.
On playwright you can change the expect timeout like this:
expect:{
timeout: 3000
}

but I don't know how to import it to this project, since the configuration is different

**Comment by Tallyb** [comment]
I guess this should work: https://playwright.dev/docs/next/test-assertions#expectconfigure

**Comment by PotatoesMaster** [comment]
I want to do the same (setting a global expect timeout).

In a test run by the Cucumber runner the timeout I pass to `expect.configure` is ignored (the default of 5000ms is used). It works as expected in a test run by the Playwright runner. ☹️

**Comment by qubaoqa** [comment]
> https://playwright.dev/docs/next/test-assertions#expectconfigure

Hi, I have the same issue, when do you change it? I change in cucumber.mjs file not sure it works or not

**Comment by Tallyb** [comment]
timeouts are defined in playwright test runner which is not used in this repo (only PW library). File an issue on the PW repo to expose the action global timeouts in the library, and then it will be available.
