### ISSUE TITLE
How could a same keyword be used as a test prerequisite for a scenario and action for an other?

### ISSUE THREAD

**Issue by z06mpaye** [Tallyb/cucumber-playwright#855]
When we test a system, we sometime have to use a keyword with different ways.

### **If I want to test the home page content:**
When I go on the home
Then I expect this
-- 
### **If i want to start from home, the home page could be a prerequisite and not the main action of the test:**
Given I go on the home
When I click on the button
Then I expect that.
...
If I clearly understand today: " go on the home" can only be used in a single context.
How could we provide a solution that can be reused as a prerequisite or as a test action (depending the aim of the test)?

**Comment by Tallyb** [comment]
I am not sure I understand your question, and this is mostly a cucumbers question. I would suggest consulting their documentation.
